language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/pip
    - vendor

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=weak

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.6
      env: DOCTRINE_VERSION=2.2.*
    - php: 5.6
      env: DOCTRINE_VERSION=2.3.*
    - php: 5.6
      env: DOCTRINE_VERSION=2.4.*
    - php: 5.6
      env: DOCTRINE_VERSION=2.5.*
    - php: 5.6
      env: DOCTRINE_VERSION=2.6.*@dev
  allow_failures:
    - php: 7.0
    - php: hhvm
    - env: DOCTRINE_VERSION=2.6.*@dev

before_script:
  - mkdir -p ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d && echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer selfupdate
  - composer config -q github-oauth.github.com $GITHUB_OAUTH_TOKEN
  - if [ "$DOCTRINE_VERSION" = "2.6.*@dev" ]; then SYMFONY_DEPRECATIONS_HELPER=strict; fi;
  - if [ "$DOCTRINE_VERSION" != "" ]; then composer require "doctrine/dbal:${DOCTRINE_VERSION}" --no-update; fi;
  - travis_wait composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:  make test
